### PR TITLE
Feature/add base agent class

### PR DESCRIPTION
**Pull request by xTumulus**
There is demo code in the actions and some //TODO comments out there, but mostly complete.

### CODE REVIEW

**Review by Asht0n16 — COMMENTED** [review]
I'm gonna do some of my work on this branch before I merge it, so we can keep the sim running on the dev branch.

**Comment by gotchoices** [comment]
I looked through the file list for the pull request, but it is a little 
hard to see just the file names in the midst of all the diff info.  Do 
you know a way to do that?

I'd like to understand:

  * if there are any pre-existing files that have been changed, what are
    they?
  * and are your new files limited to lib/agent3.js and lib/agent3/ and
    sim/simcloud?

I see that agent2.js has been run through a beautifier.  While I 
appreciate how this has made it easier to read the code, I'm not in 
favor of expanding/indenting all the debug statements.  I'd rather keep 
those as one-liners so they are easy to factor out when reading the 
code.  So I'd prefer either:

  * leave agent2.js unbeautified; or
  * re-smash all the debug lines (would probably have to be done by hand);

Also, I like the PR workflow (that you are evidently using) better than 
having you commit to the main MyCHIPs repo (as we had originally 
discussed).  I'm guessing under this model, you don't really need 
permissions on the main repo at all.  Is that correct?

**Comment by Asht0n16** [comment]
GitHub provides pretty good diff tools when PRs are made. Clicking on the "Files Changed" tab at the top will show all the relevant diffs. 
We have not changed any files outside of agent3.ts/js or the agent3 folder. Except for package.json and package-lock.json and a folder for unit tests we hope to write one day.
There are also some new files in a @types folder that are used for typescript, but I think that's all of our new files. 

I'll go fix the comments in agent2.js before merging this into our dev branch.

And yes, we haven't merged anything into the master branch, and don't plan to without your permission.

**Comment by gotchoices** [comment]
So does lib/@types/global.d.ts have to live just under lib?  Is that some standard?  Or can the global.d.ts be inside lib/agent3?  Maybe it gets referenced from lib/agent3.js?

**Comment by jack40tall** [comment]
Yeah, that's exactly what is happening. Having the @types folder just under lib gives agent3.ts access to the typings it contains, which makes development much easier.

**Review by Asht0n16 — CHANGES_REQUESTED** [review]
I'm gonna do some of my work on this branch before I merge it, so we can keep the sim running on the dev branch.

**Pull request closed without merging**
